trigger:
  branches:
    include:
      - main
      - food-page

pool:
  vmImage: ubuntu-latest

steps:
  # Build
  - script: echo "Building Cat Cafe Food Ordering feature on $(Build.SourceBranchName)"
    displayName: "Build step"

  # Success
  - script: |
      curl -H "Content-Type: application/json" \
           -X POST \
           -d "{\"content\": \"Build succeeded on branch **$(Build.SourceBranchName)** (Build No: $(Build.BuildNumber))\"}" \
           https://discord.com/api/webhooks/1405414484184530985/rWsABiW21gSr9cTAEE3wgYdgdJttYtsvuKuxECOtYlCehC1Kunsng-30Jnkb2siTmcOY
    displayName: "Discord Notify (Success)"
    condition: succeeded()

  # Fail
  - script: |
      curl -H "Content-Type: application/json" \
           -X POST \
           -d "{\"content\": \"Build failed on branch **$(Build.SourceBranchName)** (Build No: $(Build.BuildNumber))\"}" \
           https://discord.com/api/webhooks/1405414484184530985/rWsABiW21gSr9cTAEE3wgYdgdJttYtsvuKuxECOtYlCehC1Kunsng-30Jnkb2siTmcOY
    displayName: "Discord Notify (Failure)"
    condition: failed()
