trigger:
  branches:
    include:
      - adoptionrequest 

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- task: NodeTool@0
  displayName: 'Use Node.js 22.x'
  inputs:
    versionSpec: '22.x'

- script: npm install
  displayName: 'Install dependencies'

- script: npm run lint
  displayName: 'ESLint'
  #continueOnError: true

# Run Jest and produce JUnit for Azure Test tab
- script: npm test -- --ci --reporters=default --reporters=jest-junit
  displayName: 'Run Jest tests'

- task: PublishTestResults@2
  displayName: 'Publish jest-junit results'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '$(workingDirectory)/test-results/jest/junit.xml'
    failTaskOnFailedTests: true
    testRunTitle: 'cat-detail tests'

# - task: PublishBuildArtifacts@1
#   displayName: 'Publish coverage artifact'
#   inputs:
#     PathtoPublish: '$(workingDirectory)/coverage'
#     ArtifactName: 'coverage'
#     publishLocation: 'Container'