trigger:
  branches:
    include: [ main, food-management, dev ]

pool:
  vmImage: 'ubuntu-latest'

variables:
  NODE_VERSION: '22.x'

steps:
  - checkout: self

  - task: NodeTool@0
    displayName: 'Use Node $(NODE_VERSION)'
    inputs:
      versionSpec: '$(NODE_VERSION)'

  - script: node -v && npm -v
    displayName: 'Show Node & npm versions'

  - script: npm ci
    displayName: 'Install dependencies (npm ci)'

  - script: npm run lint
    displayName: 'Run ESLint'

  - script: npm test
    displayName: 'Run unit tests'

  - script: npm run smoke
    displayName: 'Run smoke test'