trigger:
  branches:
    include:
      - '*'

variables:
  buildConfiguration: 'Release'

stages:
- stage: 'Build'
  displayName: 'Build the web application'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'ubuntu-latest'
      demands:
      - npm

    steps:

    - task: Npm@1
      displayName: 'Run npm install'
      inputs:
        verbose: false

    - task: gulp@1
      displayName: 'Run gulp tasks'

    - task: NodeTool@0
      displayName: 'Install Node.js 22.x'
      inputs:
        versionSpec: '22.x'

    - script: npm ci
      displayName: 'Install dependencies'

    - script: npm test
      displayName: 'Run unit tests'

    - script: npm run lint
      displayName: 'Lint'

- stage: 'Deploy'
  displayName: 'Deploy the web application'
  dependsOn: Build
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    environment: dev
    variables:
    - group: Release
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - task: AzureWebApp@1
            displayName: 'Azure App Service Deploy: website'
            inputs:
              azureSubscription: 'Resource Manager - ASD Cat Cafe'
              appName: '$(WebAppName)'
              package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip'