trigger:
- booking-management

pool:
  vmImage: ubuntu-latest

jobs:
  - job: BMBuild
    displayName: 'Install dependencies and Node.js'
    steps:
      - task: NodeTool@0
        inputs: 
          versionSpec: '22.x'
      - script: npm ci

  - job: BookingTests
    displayName: 'Booking Tests'
    steps:
      run: npm test
      