# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- booking-management

pool:
  vmImage: ubuntu-latest

jobs:
  - job: BMBuild
    displayName: 'Install dependencies and Node.js'
    steps:
      - task: NodeTool@0
        inputs: 
          versionSpec: '22.x'
      - script: npm ci

  - job: BMTests
    displayName: 'Booking Management Tests'
    steps:
      - script: echo running booking management tests
      