trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '22.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'Install dependencies'
  workingDirectory: main

- script: npm run lint
  displayName: 'ESLint'
  workingDirectory: main

- script: npm run test:report
  displayName: 'Run unit tests with Jest'
  workingDirectory: main

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'test-results/jest/junit.xml'
    failTaskOnFailedTests: true
  condition: succeededOrFailed()