trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self

  - task: NodeTool@0
    displayName: 'Use Node.js 22.x'
    inputs:
      versionSpec: '22.x'

  - script: npm ci
    displayName: 'Install dependencies'
    workingDirectory: main


  - script: npm test
    displayName: 'Run unit tests (Jest) + coverage'
    workingDirectory: main

  - script: npm run lint
    displayName: 'Lint'
    workingDirectory: main
    
  - task: PublishTestResults@2
    displayName: 'Publish test results'
    condition: always()
    inputs:
      testResultsFormat: 'JUnit'                 
      testResultsFiles: 'main/test-results/jest/junit.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)'
      testRunTitle: 'Jest tests'
      failTaskOnFailedTests: false

  - task: PublishCodeCoverageResults@2
    displayName: 'Publish code coverage'
    condition: always()
    inputs:
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/main/coverage/lcov.info'
      pathToSources: '$(System.DefaultWorkingDirectory)/main'
      failIfCoverageEmpty: false