trigger:
- booking-management

pool:
  vmImage: ubuntu-latest

stages:
- stage: Test
  displayName: "Run test cases using Jest"
  jobs:
  - job: test
    displayName: "Run test cases"

    steps:
      - task: NodeTool@0
        displayName: 'Install Dependencies'
        inputs: 
          versionSpec: '22.x'

      - task: Npm@1
        inputs:
          command: 'install'

      - task: Npm@1
        inputs:
          command: 'custom'
          customCommand: 'run test'
      