trigger:
  branches:
    include:
      - '*'

variables:
  buildConfiguration: 'Release'

stages:
- stage: 'Build'
  displayName: 'Build the web application'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'ubuntu-latest'
      demands:
      - npm

    steps:

    - task: Npm@1
      displayName: 'Run npm install'
      inputs:
        verbose: false

    - task: NodeTool@0
      displayName: 'Install Node.js 22.x'
      inputs:
        versionSpec: '22.x'

    - script: npm ci
      displayName: 'Install dependencies'

    - script: npm run build
      displayName: 'Build project'

    - script: npm test
      displayName: 'Run unit tests'

    - script: npm run lint
      displayName: 'Lint'

  # Copy project files to artifact staging directory
    - task: CopyFiles@2
      inputs:
        sourceFolder: '$(Build.SourcesDirectory)'
        contents: |
          public/**
        targetFolder: '$(Build.ArtifactStagingDirectory)'
      displayName: 'Copy project files'

  # Publish pipeline artifact
    - task: PublishPipelineArtifact@1
      inputs:
        artifactName: 'nodejs-app'
        targetPath: '$(Build.ArtifactStagingDirectory)'
      displayName: 'Publish pipeline artifact'

- stage: 'Deploy'
  displayName: 'Deploy the web application'
  dependsOn: Build
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    environment: dev
    variables:
    - group: Release
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - task: AzureWebApp@1
            displayName: 'Azure App Service Deploy: website'
            inputs:
              azureSubscription: 'Resource Manager - ASD Cat Cafe'
              appName: '$(WebAppName)'
              package: '$(Build.ArtifactStagingDirectory)/**/*.zip'