# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- food-management

pool:
  vmImage: ubuntu-latest

jobs:
  - job: FMBuild
    displayName: 'Install dependencies and Node.js'
    steps:
      - task: NodeTool@0
        inputs: 
          versionSpec: '22.x'
      - script: npm ci
  - job: FMTests
    displayName: 'Food Management Tests'
    steps:
      - script: echo running food management tests