trigger:
- booking-management

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    displayName: 'Install Dependencies'
    inputs: 
      versionSpec: '22.x'
  - script: npm ci

  - task: PublishTestResults@2
    displayName: 'Booking Tests'
    steps:
    - script: npm test
      