trigger:
- test/booking-management

pool:
  vmImage: ubuntu-latest

stages:
- stage: Test
  displayName: "Run Test Cases Using Jest"
  jobs:
  - job: test
    displayName: "Run Test Cases"

    steps:
      - task: NodeTool@0
        displayName: 'Install Node'
        inputs: 
          versionSpec: '22.x'

      - task: Npm@1
        displayName: 'Install Npm'
        inputs:
          command: 'install'

      - task: Npm@1
        displayName: 'Run Tests'
        inputs:
          command: 'custom'
          customCommand: 'run test'
      