trigger:
  branches:
    include:
      - main
      - food-page

pr:
  branches:
    include:
      - main
      - food-page

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: Use Node.js

  - script: npm run lint
    displayName: Lint

  - script: npm test
    displayName: Unit & integration tests

  - script: npm run smoke
    displayName: Smoke test
