trigger:

  branches:
    include:
      - dev

pool:
  vmImage: ubuntu-latest

jobs:
  - job: BMBuild
    displayName: 'Install dependencies and Node.js'
    steps:
      - task: NodeTool@0
        inputs: 
          versionSpec: '22.x'
      - script: npm ci

  - job: BMTests
    displayName: 'Booking Management Tests'
    steps:
      - script: echo running booking management tests