trigger:
  branches:
    include: [ main, food-page ]

pr:
  branches:
    include: [ main, food-page ]

pool:
  vmImage: 'ubuntu-latest'

variables:
  NODE_VERSION: '20.x'

steps:
  - checkout: self

  - task: NodeTool@0
    displayName: 'Use Node $(NODE_VERSION)'
    inputs:
      versionSpec: '$(NODE_VERSION)'

  - script: node -v && npm -v
    displayName: 'Show Node & npm'

  - script: npm ci
    displayName: 'Install deps (npm ci)'

  - script: npm run lint
    displayName: 'Lint'

  - script: npm test
    displayName: 'Unit & integration tests'

  - script: npm run smoke
    displayName: 'Smoke test'
