trigger:
  branches:
    include:
      - '*'

stages:
- stage: 'Build'
  displayName: 'Build the web application'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'ubuntu-20.04'
      demands:
      - npm

    variables:
      wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
      dotnetSdkVersion: '6.x'

    steps:

    - task: Npm@1
      displayName: 'Run npm install'
      inputs:
        verbose: false

    - script: './node_modules/.bin/node-sass $(wwwrootDir) --output $(wwwrootDir)'
      displayName: 'Compile Sass assets'

    - task: gulp@1
      displayName: 'Run gulp tasks'

    - script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
      displayName: 'Write build info'
      workingDirectory: $(wwwrootDir)

    - publish: '$(Build.ArtifactStagingDirectory)'
      artifact: drop

    - task: NodeTool@0
      displayName: 'Install Node.js 22.x'
      inputs:
        versionSpec: '22.x'

    - script: npm ci
      displayName: 'Install dependencies'

    - script: npm test
      displayName: 'Run unit tests'

    - script: npm run lint
      displayName: 'Lint'

  