trigger:

  branches:
    include:
      - '*'

pool:
  vmImage: ubuntu-latest

jobs:
  - job: Build
    displayName: 'Install dependencies and Node.js'
    steps:
      - task: NodeTool@0
        inputs: 
          versionSpec: '22.x'
      - script: npm ci

  - job: Lint
    displayName: 'Lint'
    steps:
      - script: npm run lint

  - job: Tests
    displayName: 'Cat Display Tests'
    steps:
      - script: echo running cat display tests